const fs = require("fs");
const path = require("path");

const appRoutes = require("../dist/output/app-routes");
const { generateFile } = require("./generate-file");

const OUTPUT_FILE = path.join(__dirname, "..", "dist/output/imports.jsx");

generateImports();

function generateImports() {
  let fileContent =
    "// AUTO-GENERATED FILE – DO NOT EDIT.\n//" +
    "\n// This file defines the imports of all the components." +
    "\n// Generated by scripts/generate-imports.js";
  const generated = generateStatements(appRoutes);

  for (const importStatement of generated.imports) {
    fileContent = fileContent.concat(`\n${importStatement}\n`);
  }

  fileContent = fileContent.concat("\n\nexport default {\n");

  for (const exportItem of generated.exports) {
    fileContent = fileContent.concat(
      `'${Object.keys(exportItem).at(0)}': ${Object.values(exportItem).at(0)},\n`,
    );
  }

  fileContent = fileContent.concat("}\n");

  generateFile(OUTPUT_FILE, fileContent)
    .then(() => {
      console.log(
        "react-native-app-router: imports.js generated successfully.",
      );
    })
    .catch((err) => {
      console.error("react-native-app-router - generateImports:", err);
    });
}

function generateStatements(route) {
  const imports = [];
  const exports = [];

  const generated = generateStatementsForRoute(route);
  imports.push(...generated.imports);
  exports.push(...generated.exports);

  for (const child of route.children) {
    const generated = generateStatements(child);

    imports.push(...generated.imports);
    exports.push(...generated.exports);
  }

  return { imports, exports };
}

function generateStatementsForRoute(route) {
  const imports = [];
  const exports = [];

  const normalizedComponentName = capitalize(
    route.segment.replaceAll("[", "").replaceAll("]", ""),
  ).replaceAll("-", "");
  if (route.layoutFile) {
    const component = `${normalizedComponentName}Layout`;

    imports.push(
      `import ${component} from '../../../../src/${route.layoutFile}'`,
    );
    exports.push({ [route.layoutFile]: component });
  }

  imports.push(
    `import ${normalizedComponentName} from '../../../../src/${route.screenFile}'`,
  );
  exports.push({ [route.screenFile]: normalizedComponentName });

  return { imports, exports };
}

function capitalize(string) {
  return string.charAt(0).toUpperCase() + string.slice(1);
}
